// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zoobee.Infrastructure.Parsers.ParsedDataStorage.ParsersDbContext;

#nullable disable

namespace Zoobee.Web.Migrations
{
    [DbContext(typeof(ParsersDbContext))]
    [Migration("20251120113749_Parsers20")]
    partial class Parsers20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.ParsedDataStorage.ParsedDataEntities.ParsedDataIdentifiers.ParsedProductIdentifierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("ParsedDatasOfProduct")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<string>("ParsedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParsedUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParsedProductsIdentifiers");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.ParsedDataStorage.ParsedDataEntities.ParsedProductHolder.ParsedProductHolder<Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastTransformed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParsedUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("parsedProductModelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("parsedProductModelId");

                    b.ToTable("Zoobazar_ParsedProducts");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Offer", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("Available")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "available");

                    b.Property<string>("DateDelivery")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "dateDelivery");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("InternalCode")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "internalCode");

                    b.Property<bool?>("IsAvailDelivery")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isAvailDelivery");

                    b.Property<bool?>("IsMedicine")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "isMedicine");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "label");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "link");

                    b.Property<string>("MindboxId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "mindboxId");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "quantity");

                    b.Property<string>("Sale")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "sale");

                    b.Property<bool?>("Selected")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "selected");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Sku")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "sku");

                    b.Property<string>("Weight")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "weight");

                    b.Property<string>("XmlId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "xmlId");

                    b.Property<Guid?>("ZoobazarParsedProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoobazarParsedProductId");

                    b.ToTable("ZoobazarOffers");

                    b.HasAnnotation("Relational:JsonPropertyName", "offers");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Property", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.HasKey("PropertyId");

                    b.HasIndex("OfferId");

                    b.ToTable("Property");

                    b.HasAnnotation("Relational:JsonPropertyName", "properties");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Tab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "code");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Sort")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "sort");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "value");

                    b.Property<Guid?>("ZoobazarParsedProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoobazarParsedProductId");

                    b.ToTable("ZoobazarTabs");

                    b.HasAnnotation("Relational:JsonPropertyName", "tabs");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Id")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "link");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.HasKey("TagId");

                    b.HasIndex("OfferId");

                    b.ToTable("Tag");

                    b.HasAnnotation("Relational:JsonPropertyName", "tags");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Advantages")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "advantages");

                    b.Property<string>("BrandId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "brandId");

                    b.Property<string>("Composition")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "composition");

                    b.Property<bool?>("HaveOffers")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "haveOffers");

                    b.Property<string>("OffersProperty")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "offersProperty");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "productId");

                    b.Property<string>("ProductName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "productName");

                    b.Property<string>("ProductXmlId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "productXmlId");

                    b.Property<string>("SectionId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "sectionId");

                    b.Property<string>("SectionName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "sectionName");

                    b.Property<string>("SectionPath")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "sectionPath");

                    b.Property<string>("SiteId")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "siteId");

                    b.HasKey("Id");

                    b.ToTable("ZoobazarParsedProducts");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.ParsedDataStorage.ParsedDataEntities.ParsedProductHolder.ParsedProductHolder<Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct>", b =>
                {
                    b.HasOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct", "parsedProductModel")
                        .WithMany()
                        .HasForeignKey("parsedProductModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ParsedProductHolderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ParsedProductHolderId");

                            b1.ToTable("Zoobazar_ParsedProducts");

                            b1.WithOwner()
                                .HasForeignKey("ParsedProductHolderId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ParsedProductHolderId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ParsedProductHolderId");

                            b1.ToTable("Zoobazar_ParsedProducts");

                            b1.WithOwner()
                                .HasForeignKey("ParsedProductHolderId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("parsedProductModel");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Offer", b =>
                {
                    b.HasOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct", null)
                        .WithMany("Offers")
                        .HasForeignKey("ZoobazarParsedProductId");

                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.DiscountPoints", "DiscountPoints", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Formatted")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "formatted");

                            b1.Property<double?>("Raw")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "raw");

                            b1.HasKey("OfferId");

                            b1.ToTable("ZoobazarOffers");

                            b1.HasAnnotation("Relational:JsonPropertyName", "discountPoints");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Base")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "base");

                            b1.Property<double?>("BaseRaw")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "baseRaw");

                            b1.Property<string>("Currency")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "currency");

                            b1.Property<int?>("DiscountPercent")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "discountPercent");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Result")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "result");

                            b1.Property<double?>("ResultRaw")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "resultRaw");

                            b1.Property<double?>("SubscriptionRaw")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "subscriptionRaw");

                            b1.HasKey("OfferId");

                            b1.ToTable("ZoobazarOffers");

                            b1.HasAnnotation("Relational:JsonPropertyName", "price");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");

                            b1.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.PriceFormat", "Format", b2 =>
                                {
                                    b2.Property<Guid>("PriceOfferId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("DecimalPoint")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "decPoint");

                                    b2.Property<int?>("Decimals")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "decimals");

                                    b2.Property<string>("Pattern")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "pattern");

                                    b2.Property<string>("ThousandsSeparator")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "thousandsSep");

                                    b2.HasKey("PriceOfferId");

                                    b2.ToTable("ZoobazarOffers");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "format");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceOfferId");
                                });

                            b1.Navigation("Format");
                        });

                    b.Navigation("DiscountPoints");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Property", b =>
                {
                    b.HasOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Offer", null)
                        .WithMany("Properties")
                        .HasForeignKey("OfferId");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Tab", b =>
                {
                    b.HasOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct", null)
                        .WithMany("Tabs")
                        .HasForeignKey("ZoobazarParsedProductId");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Tag", b =>
                {
                    b.HasOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Offer", null)
                        .WithMany("Tags")
                        .HasForeignKey("OfferId");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct", b =>
                {
                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Brand", "Brand", b1 =>
                        {
                            b1.Property<Guid>("ZoobazarParsedProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "id");

                            b1.Property<string>("Link")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "link");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "name");

                            b1.HasKey("ZoobazarParsedProductId");

                            b1.ToTable("ZoobazarParsedProducts");

                            b1.HasAnnotation("Relational:JsonPropertyName", "brand");

                            b1.WithOwner()
                                .HasForeignKey("ZoobazarParsedProductId");
                        });

                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.CurrentLocation", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("ZoobazarParsedProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "CODE");

                            b1.Property<int?>("FreeDelivery")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "FREE_DELIVERY");

                            b1.Property<string>("Hours")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "HOURS");

                            b1.Property<int>("Id")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "ID");

                            b1.Property<List<string>>("Location")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasAnnotation("Relational:JsonPropertyName", "LOCATION");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "NAME");

                            b1.Property<bool?>("PickupOnly")
                                .HasColumnType("boolean")
                                .HasAnnotation("Relational:JsonPropertyName", "PICKUP_ONLY");

                            b1.Property<List<int>>("Store")
                                .IsRequired()
                                .HasColumnType("integer[]")
                                .HasAnnotation("Relational:JsonPropertyName", "STORE");

                            b1.HasKey("ZoobazarParsedProductId");

                            b1.ToTable("ZoobazarParsedProducts");

                            b1.HasAnnotation("Relational:JsonPropertyName", "currentLocation");

                            b1.WithOwner()
                                .HasForeignKey("ZoobazarParsedProductId");
                        });

                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ZoobazarParsedProductId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Count")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "count");

                            b1.Property<double?>("Value")
                                .HasColumnType("double precision")
                                .HasAnnotation("Relational:JsonPropertyName", "value");

                            b1.HasKey("ZoobazarParsedProductId");

                            b1.ToTable("ZoobazarParsedProducts");

                            b1.HasAnnotation("Relational:JsonPropertyName", "rating");

                            b1.WithOwner()
                                .HasForeignKey("ZoobazarParsedProductId");
                        });

                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Reviews", "Reviews", b1 =>
                        {
                            b1.Property<Guid>("ZoobazarParsedProductId")
                                .HasColumnType("uuid");

                            b1.HasKey("ZoobazarParsedProductId");

                            b1.ToTable("ZoobazarParsedProducts");

                            b1.HasAnnotation("Relational:JsonPropertyName", "reviews");

                            b1.WithOwner()
                                .HasForeignKey("ZoobazarParsedProductId");

                            b1.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ReviewStatistic", "Statistic", b2 =>
                                {
                                    b2.Property<Guid>("ReviewsZoobazarParsedProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool?>("Allow")
                                        .HasColumnType("boolean")
                                        .HasAnnotation("Relational:JsonPropertyName", "allow");

                                    b2.Property<int?>("Count")
                                        .HasColumnType("integer")
                                        .HasAnnotation("Relational:JsonPropertyName", "count");

                                    b2.Property<bool?>("IsExists")
                                        .HasColumnType("boolean")
                                        .HasAnnotation("Relational:JsonPropertyName", "isExists");

                                    b2.Property<double?>("Vote")
                                        .HasColumnType("double precision")
                                        .HasAnnotation("Relational:JsonPropertyName", "vote");

                                    b2.HasKey("ReviewsZoobazarParsedProductId");

                                    b2.ToTable("ZoobazarParsedProducts");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "statistic");

                                    b2.WithOwner()
                                        .HasForeignKey("ReviewsZoobazarParsedProductId");
                                });

                            b1.Navigation("Statistic")
                                .IsRequired();
                        });

                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.TestData", "Test", b1 =>
                        {
                            b1.Property<Guid>("ZoobazarParsedProductId")
                                .HasColumnType("uuid");

                            b1.HasKey("ZoobazarParsedProductId");

                            b1.ToTable("ZoobazarParsedProducts");

                            b1.HasAnnotation("Relational:JsonPropertyName", "test");

                            b1.WithOwner()
                                .HasForeignKey("ZoobazarParsedProductId");

                            b1.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.PropertyData", "Brand", b2 =>
                                {
                                    b2.Property<Guid>("TestDataZoobazarParsedProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Active")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "ACTIVE");

                                    b2.Property<string>("IblockId")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "IBLOCK_ID");

                                    b2.Property<string>("Id")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "ID");

                                    b2.Property<string>("Name")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "NAME");

                                    b2.HasKey("TestDataZoobazarParsedProductId");

                                    b2.ToTable("ZoobazarParsedProducts");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "BRAND");

                                    b2.WithOwner()
                                        .HasForeignKey("TestDataZoobazarParsedProductId");
                                });

                            b1.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.PropertyData", "Gallery", b2 =>
                                {
                                    b2.Property<Guid>("TestDataZoobazarParsedProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Active")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "ACTIVE");

                                    b2.Property<string>("IblockId")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "IBLOCK_ID");

                                    b2.Property<string>("Id")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "ID");

                                    b2.Property<string>("Name")
                                        .HasColumnType("text")
                                        .HasAnnotation("Relational:JsonPropertyName", "NAME");

                                    b2.HasKey("TestDataZoobazarParsedProductId");

                                    b2.ToTable("ZoobazarParsedProducts");

                                    b2.HasAnnotation("Relational:JsonPropertyName", "GALLERY");

                                    b2.WithOwner()
                                        .HasForeignKey("TestDataZoobazarParsedProductId");
                                });

                            b1.Navigation("Brand");

                            b1.Navigation("Gallery");
                        });

                    b.OwnsOne("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.User", "User", b1 =>
                        {
                            b1.Property<Guid>("ZoobazarParsedProductId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Id")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "id");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "name");

                            b1.Property<string>("PersonalPhone")
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "personalPhone");

                            b1.HasKey("ZoobazarParsedProductId");

                            b1.ToTable("ZoobazarParsedProducts");

                            b1.HasAnnotation("Relational:JsonPropertyName", "user");

                            b1.WithOwner()
                                .HasForeignKey("ZoobazarParsedProductId");
                        });

                    b.Navigation("Brand")
                        .IsRequired();

                    b.Navigation("CurrentLocation");

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("Reviews")
                        .IsRequired();

                    b.Navigation("Test")
                        .IsRequired();

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.Offer", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Storage.ParsedDataEntities.ParsedProductsModels.Zoobazar.ZoobazarParsedProduct", b =>
                {
                    b.Navigation("Offers");

                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
