// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zoobee.Infrastructure.Repositoties;

#nullable disable

namespace ZooStores.Web.Migrations
{
    [DbContext(typeof(ZoobeeAppDbContext))]
    [Migration("20250927193809_zoo27.09.2025")]
    partial class zoo27092025
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryOptionEntitySellingSlotEntity", b =>
                {
                    b.Property<Guid>("DeliveryOptionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSlotsId")
                        .HasColumnType("uuid");

                    b.HasKey("DeliveryOptionsId", "ProductSlotsId");

                    b.HasIndex("ProductSlotsId");

                    b.ToTable("DeliveryOptionEntitySellingSlotEntity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SelfPickupOptionEntitySellingSlotEntity", b =>
                {
                    b.Property<Guid>("ProductSlotsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelfPickupOptionsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductSlotsId", "SelfPickupOptionsId");

                    b.HasIndex("SelfPickupOptionsId");

                    b.ToTable("SelfPickupOptionEntitySellingSlotEntity");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Catalog.Reviews.ReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<Guid>("ReviewedProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedProductId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Catalog.Tags.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BaseProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedTagName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("BaseProductEntityId");

                    b.HasIndex("NormalizedTagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Creators.BrandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<string>("NormalizedBrandName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedBrandName")
                        .IsUnique();

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Creators.CreatorCountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("NormalizedCountryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CreatorCountries");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Geography.DeliveryAreaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedAreaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SellerCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AreaName")
                        .IsUnique();

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("DeliveryAreas");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Geography.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedAddress")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedCity")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.CreatorCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NormalizedCompanyName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCompanyName")
                        .IsUnique();

                    b.ToTable("CreatorCompanies");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.ProductLineupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("LineupDescription")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)");

                    b.Property<string>("LineupName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NormalizedLineupName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("ProductsLineups");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.SellerCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NormalizedCompanyName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedCompanyName")
                        .IsUnique();

                    b.ToTable("SellerCompanies");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.ZooStoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("ClosingTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<TimeOnly?>("OpeningTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("SellerCompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("StoreType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("ZooStores");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Identity.Role.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("BaseApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Media.MediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileLocalURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileLocalURL")
                        .IsUnique();

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.BaseProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorCompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorCountryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("EAN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<decimal>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<List<string>>("MediaURI")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PetKindId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductLineUpId")
                        .HasColumnType("uuid");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<string>("UPC")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CreatorCompanyId");

                    b.HasIndex("CreatorCountryId");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("PetKindId");

                    b.HasIndex("ProductLineUpId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("BaseProductEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.PetKindEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedPetKindName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PetKindName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPetKindName")
                        .IsUnique();

                    b.ToTable("PetKinds");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.SellingSlotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultSlotPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ResultPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SellerCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerCompanyId");

                    b.ToTable("SellingSlots");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.SellingsInformation.DeliveryOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeliveryAreaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeliveryPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryAreaId");

                    b.ToTable("DeliveryOptions");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.SellingsInformation.SelfPickupOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeliveryToPointCost")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan>("DeliveryToPointTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvaibableOnlinePayment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvaibableToBook")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PickupPointLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PickupPointLocationId");

                    b.ToTable("SelfPickupOptions");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Identity.Users.AdminUser", b =>
                {
                    b.HasBaseType("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Identity.Users.CustomerUser", b =>
                {
                    b.HasBaseType("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser");

                    b.Property<int>("BornYear")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Identity.Users.OrganisationUser", b =>
                {
                    b.HasBaseType("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser");

                    b.HasDiscriminator().HasValue("Organisation");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.FoodProductEntity.FoodProductEntity", b =>
                {
                    b.HasBaseType("Zoobee.Domain.DataEntities.Products.BaseProductEntity");

                    b.Property<int>("FoodType")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProductWeightGramms")
                        .HasColumnType("numeric");

                    b.HasDiscriminator().HasValue("FoodProductEntity");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.ToiletProductEntity.ToiletProductEntity", b =>
                {
                    b.HasBaseType("Zoobee.Domain.DataEntities.Products.BaseProductEntity");

                    b.Property<int>("ToiletType")
                        .HasColumnType("integer");

                    b.Property<float?>("VolumeLiters")
                        .HasColumnType("real");

                    b.HasDiscriminator().HasValue("ToiletProductEntity");
                });

            modelBuilder.Entity("DeliveryOptionEntitySellingSlotEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.SellingsInformation.DeliveryOptionEntity", null)
                        .WithMany()
                        .HasForeignKey("DeliveryOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Products.SellingSlotEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductSlotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Identity.Role.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Identity.Role.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Identity.Users.BaseApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SelfPickupOptionEntitySellingSlotEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Products.SellingSlotEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductSlotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.SellingsInformation.SelfPickupOptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SelfPickupOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Catalog.Reviews.ReviewEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Products.BaseProductEntity", "ReviewedProduct")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Identity.Users.CustomerUser", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ReviewEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ReviewEntityId");

                            b1.ToTable("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ReviewEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ReviewEntityId");

                            b1.ToTable("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("ReviewedProduct");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Catalog.Tags.TagEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Products.BaseProductEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("BaseProductEntityId");

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("TagEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("TagEntityId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TagEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TagEntityId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Creators.BrandEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("BrandEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("BrandEntityId");

                            b1.ToTable("Brands");

                            b1.WithOwner()
                                .HasForeignKey("BrandEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("BrandEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("BrandEntityId");

                            b1.ToTable("Brands");

                            b1.WithOwner()
                                .HasForeignKey("BrandEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Creators.CreatorCountryEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("CreatorCountryEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("CreatorCountryEntityId");

                            b1.ToTable("CreatorCountries");

                            b1.WithOwner()
                                .HasForeignKey("CreatorCountryEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("CreatorCountryEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CreatorCountryEntityId");

                            b1.ToTable("CreatorCountries");

                            b1.WithOwner()
                                .HasForeignKey("CreatorCountryEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Geography.DeliveryAreaEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Manufactures.SellerCompanyEntity", "SellerCompany")
                        .WithMany()
                        .HasForeignKey("SellerCompanyId");

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("DeliveryAreaEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("DeliveryAreaEntityId");

                            b1.ToTable("DeliveryAreas");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryAreaEntityId");
                        });

                    b.OwnsMany("Zoobee.Domain.DataEntities.Environment.Geography.GeoPoint", "GeoArea", b1 =>
                        {
                            b1.Property<Guid>("DeliveryAreaEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("DeliveryAreaEntityId", "Id");

                            b1.ToTable("DeliveryAreas_GeoArea");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryAreaEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DeliveryAreaEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DeliveryAreaEntityId");

                            b1.ToTable("DeliveryAreas");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryAreaEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("GeoArea");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Geography.LocationEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("LocationEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("LocationEntityId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Environment.Geography.GeoPoint", "GeoPoint", b1 =>
                        {
                            b1.Property<Guid>("LocationEntityId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");

                            b1.HasKey("LocationEntityId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("LocationEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("LocationEntityId");

                            b1.ToTable("Locations");

                            b1.WithOwner()
                                .HasForeignKey("LocationEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("GeoPoint")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.CreatorCompanyEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("CreatorCompanyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("CreatorCompanyEntityId");

                            b1.ToTable("CreatorCompanies");

                            b1.WithOwner()
                                .HasForeignKey("CreatorCompanyEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("CreatorCompanyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CreatorCompanyEntityId");

                            b1.ToTable("CreatorCompanies");

                            b1.WithOwner()
                                .HasForeignKey("CreatorCompanyEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.ProductLineupEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Creators.BrandEntity", "Brand")
                        .WithMany("BrandsLineups")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ProductLineupEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ProductLineupEntityId");

                            b1.ToTable("ProductsLineups");

                            b1.WithOwner()
                                .HasForeignKey("ProductLineupEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ProductLineupEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductLineupEntityId");

                            b1.ToTable("ProductsLineups");

                            b1.WithOwner()
                                .HasForeignKey("ProductLineupEntityId");
                        });

                    b.Navigation("Brand");

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.SellerCompanyEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("SellerCompanyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("SellerCompanyEntityId");

                            b1.ToTable("SellerCompanies");

                            b1.WithOwner()
                                .HasForeignKey("SellerCompanyEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("SellerCompanyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SellerCompanyEntityId");

                            b1.ToTable("SellerCompanies");

                            b1.WithOwner()
                                .HasForeignKey("SellerCompanyEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Manufactures.ZooStoreEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Geography.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Manufactures.SellerCompanyEntity", "SellerCompany")
                        .WithMany()
                        .HasForeignKey("SellerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ZooStoreEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ZooStoreEntityId");

                            b1.ToTable("ZooStores");

                            b1.WithOwner()
                                .HasForeignKey("ZooStoreEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ZooStoreEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ZooStoreEntityId");

                            b1.ToTable("ZooStores");

                            b1.WithOwner()
                                .HasForeignKey("ZooStoreEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Media.MediaFileEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("MediaFileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("MediaFileEntityId");

                            b1.ToTable("MediaFiles");

                            b1.WithOwner()
                                .HasForeignKey("MediaFileEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("MediaFileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MediaFileEntityId");

                            b1.ToTable("MediaFiles");

                            b1.WithOwner()
                                .HasForeignKey("MediaFileEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.BaseProductEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Creators.BrandEntity", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Manufactures.CreatorCompanyEntity", "CreatorCompany")
                        .WithMany()
                        .HasForeignKey("CreatorCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Creators.CreatorCountryEntity", "CreatorCountry")
                        .WithMany()
                        .HasForeignKey("CreatorCountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Products.PetKindEntity", "PetKind")
                        .WithMany()
                        .HasForeignKey("PetKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Manufactures.ProductLineupEntity", "ProductLineUp")
                        .WithMany()
                        .HasForeignKey("ProductLineUpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("BaseProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("BaseProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("BaseProductEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("BaseProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("BaseProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("BaseProductEntityId");
                        });

                    b.Navigation("Brand");

                    b.Navigation("CreatorCompany");

                    b.Navigation("CreatorCountry");

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("PetKind");

                    b.Navigation("ProductLineUp");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.PetKindEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("PetKindEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("PetKindEntityId");

                            b1.ToTable("PetKinds");

                            b1.WithOwner()
                                .HasForeignKey("PetKindEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("PetKindEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("PetKindEntityId");

                            b1.ToTable("PetKinds");

                            b1.WithOwner()
                                .HasForeignKey("PetKindEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.SellingSlotEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Products.BaseProductEntity", "Product")
                        .WithMany("SellingSlots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Manufactures.SellerCompanyEntity", "SellerCompany")
                        .WithMany()
                        .HasForeignKey("SellerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("SellingSlotEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("SellingSlotEntityId");

                            b1.ToTable("SellingSlots");

                            b1.WithOwner()
                                .HasForeignKey("SellingSlotEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("SellingSlotEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SellingSlotEntityId");

                            b1.ToTable("SellingSlots");

                            b1.WithOwner()
                                .HasForeignKey("SellingSlotEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SellerCompany");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.SellingsInformation.DeliveryOptionEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Geography.DeliveryAreaEntity", "DeliveryArea")
                        .WithMany()
                        .HasForeignKey("DeliveryAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("DeliveryOptionEntityId");

                            b1.ToTable("DeliveryOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOptionEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DeliveryOptionEntityId");

                            b1.ToTable("DeliveryOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOptionEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("DeliveryArea");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.SellingsInformation.SelfPickupOptionEntity", b =>
                {
                    b.HasOne("Zoobee.Domain.DataEntities.Environment.Manufactures.ZooStoreEntity", "PickupPointLocation")
                        .WithMany()
                        .HasForeignKey("PickupPointLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("SelfPickupOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("SelfPickupOptionEntityId");

                            b1.ToTable("SelfPickupOptions");

                            b1.WithOwner()
                                .HasForeignKey("SelfPickupOptionEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("SelfPickupOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SelfPickupOptionEntityId");

                            b1.ToTable("SelfPickupOptions");

                            b1.WithOwner()
                                .HasForeignKey("SelfPickupOptionEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("PickupPointLocation");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.FoodProductEntity.FoodProductEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Data_Primitives.PetAgeRange", "PetAgeRange", b1 =>
                        {
                            b1.Property<Guid>("FoodProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<long>("PetAgeWeeksMax")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("bigint");

                            b1.Property<long>("PetAgeWeeksMin")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("bigint");

                            b1.HasKey("FoodProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("FoodProductEntityId");
                        });

                    b.Navigation("PetAgeRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.ToiletProductEntity.ToiletProductEntity", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Data_Primitives.SizeDimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("ToiletProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<float>("X")
                                .HasColumnType("real");

                            b1.Property<float>("Y")
                                .HasColumnType("real");

                            b1.Property<float>("Z")
                                .HasColumnType("real");

                            b1.HasKey("ToiletProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ToiletProductEntityId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Data_Primitives.PetAgeRange", "PetAgeRange", b1 =>
                        {
                            b1.Property<Guid>("ToiletProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<long>("PetAgeWeeksMax")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("bigint");

                            b1.Property<long>("PetAgeWeeksMin")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("bigint");

                            b1.HasKey("ToiletProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ToiletProductEntityId");
                        });

                    b.Navigation("Dimensions");

                    b.Navigation("PetAgeRange");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Environment.Creators.BrandEntity", b =>
                {
                    b.Navigation("BrandsLineups");
                });

            modelBuilder.Entity("Zoobee.Domain.DataEntities.Products.BaseProductEntity", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SellingSlots");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
