<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Services\DtoMappingService\**" />
    <EmbeddedResource Remove="Interfaces\Services\DtoMappingService\**" />
    <None Remove="Interfaces\Services\DtoMappingService\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.21" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Features\Database Administration\CRUD\Brands\Commands\Delete\" />
    <Folder Include="Features\Database Administration\CRUD\Brands\Commands\Update\" />
    <Folder Include="Features\Database Administration\CRUD\Brands\Queries\Read\" />
    <Folder Include="Features\Database Administration\CRUD\CreatorCompanies\Commands\Create\" />
    <Folder Include="Features\Database Administration\CRUD\CreatorCompanies\Commands\Delete\" />
    <Folder Include="Features\Database Administration\CRUD\CreatorCompanies\Commands\Update\" />
    <Folder Include="Features\Database Administration\CRUD\CreatorCompanies\Queries\Read\" />
    <Folder Include="Features\Database Administration\CRUD\PetKinds\Commands\Create\" />
    <Folder Include="Features\Database Administration\CRUD\PetKinds\Commands\Delete\" />
    <Folder Include="Features\Database Administration\CRUD\PetKinds\Commands\Update\" />
    <Folder Include="Features\Database Administration\CRUD\PetKinds\Queries\Read\" />
    <Folder Include="Features\Database Administration\CRUD\ProductsLineups\Commands\Create\" />
    <Folder Include="Features\Database Administration\CRUD\ProductsLineups\Commands\Delete\" />
    <Folder Include="Features\Database Administration\CRUD\ProductsLineups\Commands\Update\" />
    <Folder Include="Features\Database Administration\CRUD\ProductsLineups\Queries\Read\" />
    <Folder Include="Features\Database Administration\CRUD\SellerCompanies\Commands\Create\" />
    <Folder Include="Features\Database Administration\CRUD\SellerCompanies\Commands\Delete\" />
    <Folder Include="Features\Database Administration\CRUD\SellerCompanies\Commands\Update\" />
    <Folder Include="Features\Database Administration\CRUD\SellerCompanies\Queries\Read\" />
    <Folder Include="Features\Database Administration\Parsing\Parsing Failures Handling\Commands\" />
    <Folder Include="Features\Database Administration\Parsing\Parsing Failures Handling\Queries\Validation\" />
    <Folder Include="Validation\Products\" />
    <Folder Include="Validation\Sellings\" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Zoobee.Application.Shared\Zoobee.Application.Shared.csproj" />
    <ProjectReference Include="..\Zoobee.Core\Zoobee.Domain.csproj" />
  </ItemGroup>

</Project>
