// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooStores.Infrastructure.Repositoties;

#nullable disable

namespace ZooStores.Web.Migrations
{
    [DbContext(typeof(ZooStoresDbContext))]
    [Migration("20250805102127_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryOptionEntityProductSlotEntity", b =>
                {
                    b.Property<Guid>("DeliveryOptionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSlotsId")
                        .HasColumnType("uuid");

                    b.HasKey("DeliveryOptionsId", "ProductSlotsId");

                    b.HasIndex("ProductSlotsId");

                    b.ToTable("DeliveryOptionEntityProductSlotEntity");
                });

            modelBuilder.Entity("ProductSlotEntitySelfPickupOptionEntity", b =>
                {
                    b.Property<Guid>("ProductSlotsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SelfPickupOptionsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductSlotsId", "SelfPickupOptionsId");

                    b.HasIndex("SelfPickupOptionsId");

                    b.ToTable("ProductSlotEntitySelfPickupOptionEntity");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Media.MediaFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileLocalURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FileLocalURL")
                        .IsUnique();

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.DynamicAttributes.ProductAttributeTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeName")
                        .IsUnique();

                    b.ToTable("ExtAttributesTypes");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.ExtendedAttributes.ProductAttributeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExtAttributes");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("MediaURI")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.Reviews.ReviewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rating")
                        .HasMaxLength(10)
                        .HasColumnType("numeric");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProductEntityId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.Tags.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("ProductEntityId");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.PetKindEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PetKindName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PetKindName")
                        .IsUnique();

                    b.ToTable("PetKinds");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.ProductSlotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultSlotPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsAvaibable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VetStoreEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("VetStoreEntityId");

                    b.ToTable("SellingSlots");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Clinics.VetClinicEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("locationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ownerCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("locationId");

                    b.HasIndex("ownerCompanyId");

                    b.ToTable("VetClinics");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Companies.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.EntityComponents.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LocationEntity");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Products.Categories.ProductCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Products.Delivery.DeliveryOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Polygon>("Area")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<decimal>("DeliveryCost")
                        .HasColumnType("numeric");

                    b.Property<TimeSpan>("DeliveryTime")
                        .HasColumnType("interval");

                    b.Property<List<string>>("PaymentTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("DeliveryOptions");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Products.Delivery.SelfPickupOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("AvaibableInPlace")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("DeliveryToPointCost")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("DeliveryToPointTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvaibableToBook")
                        .HasColumnType("boolean");

                    b.Property<string[]>("PaymentTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("PickupPointLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PickupPointLocationId");

                    b.ToTable("SelfPickupOptions");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Stores.VetStoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ownerCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ownerCompanyId");

                    b.ToTable("VetStores");
                });

            modelBuilder.Entity("DeliveryOptionEntityProductSlotEntity", b =>
                {
                    b.HasOne("ZooStores.Application.DtoTypes.Products.Delivery.DeliveryOptionEntity", null)
                        .WithMany()
                        .HasForeignKey("DeliveryOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooStorages.Domain.DataEntities.Products.ProductSlotEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductSlotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductSlotEntitySelfPickupOptionEntity", b =>
                {
                    b.HasOne("ZooStorages.Domain.DataEntities.Products.ProductSlotEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductSlotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooStores.Application.DtoTypes.Products.Delivery.SelfPickupOptionEntity", null)
                        .WithMany()
                        .HasForeignKey("SelfPickupOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Media.MediaFileEntity", b =>
                {
                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("MediaFileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("MediaFileEntityId");

                            b1.ToTable("MediaFiles");

                            b1.WithOwner()
                                .HasForeignKey("MediaFileEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("MediaFileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("MediaFileEntityId");

                            b1.ToTable("MediaFiles");

                            b1.WithOwner()
                                .HasForeignKey("MediaFileEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.DynamicAttributes.ProductAttributeTypeEntity", b =>
                {
                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ProductAttributeTypeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ProductAttributeTypeEntityId");

                            b1.ToTable("ExtAttributesTypes");

                            b1.WithOwner()
                                .HasForeignKey("ProductAttributeTypeEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ProductAttributeTypeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductAttributeTypeEntityId");

                            b1.ToTable("ExtAttributesTypes");

                            b1.WithOwner()
                                .HasForeignKey("ProductAttributeTypeEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.ExtendedAttributes.ProductAttributeEntity", b =>
                {
                    b.HasOne("ZooStorages.Domain.DataEntities.Products.Components.DynamicAttributes.ProductAttributeTypeEntity", "AttributeType")
                        .WithMany("AttributesOfType")
                        .HasForeignKey("AttributeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooStorages.Domain.DataEntities.Products.Components.ProductEntity", "Product")
                        .WithMany("ExtendedAttributes")
                        .HasForeignKey("ProductId");

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ProductAttributeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ProductAttributeEntityId");

                            b1.ToTable("ExtAttributes");

                            b1.WithOwner()
                                .HasForeignKey("ProductAttributeEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ProductAttributeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductAttributeEntityId");

                            b1.ToTable("ExtAttributes");

                            b1.WithOwner()
                                .HasForeignKey("ProductAttributeEntityId");
                        });

                    b.Navigation("AttributeType");

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.ProductEntity", b =>
                {
                    b.HasOne("ZooStorages.Domain.DataEntities.Products.ProductTypeEntity", "ProductType")
                        .WithMany("ProductsOfType")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Products.Components.Attributes.ManufactureAttributes", "ManufactureAttributes", b1 =>
                        {
                            b1.Property<Guid>("ProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatorCountry")
                                .HasColumnType("text");

                            b1.Property<string>("EAN_Code")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)");

                            b1.Property<string>("UPC_Code")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("character varying(12)");

                            b1.HasKey("ProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Products.Components.Attributes.PetProductAttributes", "PetInfoAttributes", b1 =>
                        {
                            b1.Property<Guid>("ProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<long?>("PetAgeWeeksMax")
                                .HasColumnType("bigint");

                            b1.Property<long?>("PetAgeWeeksMin")
                                .HasColumnType("bigint");

                            b1.Property<int?>("PetGender")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PetKindId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("PetSize")
                                .HasColumnType("integer");

                            b1.HasKey("ProductEntityId");

                            b1.HasIndex("PetKindId");

                            b1.ToTable("Products");

                            b1.HasOne("ZooStorages.Domain.DataEntities.Products.PetKindEntity", "PetKind")
                                .WithMany()
                                .HasForeignKey("PetKindId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityId");

                            b1.Navigation("PetKind");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Products.Components.Attributes.PhysicalAttributes", "PhysicalAttributes", b1 =>
                        {
                            b1.Property<Guid>("ProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Color")
                                .HasColumnType("text");

                            b1.Property<int>("ContentMeasurementsUnits")
                                .HasColumnType("integer");

                            b1.Property<List<string>>("Materials")
                                .HasColumnType("text[]");

                            b1.Property<decimal?>("WeightOfProducts")
                                .HasColumnType("numeric");

                            b1.HasKey("ProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityId");

                            b1.OwnsOne("ZooStorages.Domain.DataEntities.Products.Components.Dimensions.ProductDimensions", "Dimensions", b2 =>
                                {
                                    b2.Property<Guid>("PhysicalAttributesProductEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal?>("Heigth")
                                        .HasColumnType("numeric");

                                    b2.Property<decimal?>("Length")
                                        .HasColumnType("numeric");

                                    b2.Property<decimal?>("Width")
                                        .HasColumnType("numeric");

                                    b2.HasKey("PhysicalAttributesProductEntityId");

                                    b2.ToTable("Products");

                                    b2.WithOwner()
                                        .HasForeignKey("PhysicalAttributesProductEntityId");
                                });

                            b1.Navigation("Dimensions");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ProductEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductEntityId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("ManufactureAttributes")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("PetInfoAttributes")
                        .IsRequired();

                    b.Navigation("PhysicalAttributes")
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.Reviews.ReviewEntity", b =>
                {
                    b.HasOne("ZooStorages.Domain.DataEntities.Products.Components.ProductEntity", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductEntityId");

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ReviewEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ReviewEntityId");

                            b1.ToTable("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ReviewEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ReviewEntityId");

                            b1.ToTable("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.Tags.TagEntity", b =>
                {
                    b.HasOne("ZooStorages.Domain.DataEntities.Products.Components.ProductEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("ProductEntityId");

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("TagEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("TagEntityId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("TagEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("TagEntityId");

                            b1.ToTable("Tags");

                            b1.WithOwner()
                                .HasForeignKey("TagEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.PetKindEntity", b =>
                {
                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("PetKindEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("PetKindEntityId");

                            b1.ToTable("PetKinds");

                            b1.WithOwner()
                                .HasForeignKey("PetKindEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("PetKindEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("PetKindEntityId");

                            b1.ToTable("PetKinds");

                            b1.WithOwner()
                                .HasForeignKey("PetKindEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.ProductSlotEntity", b =>
                {
                    b.HasOne("ZooStorages.Domain.DataEntities.Products.Components.ProductEntity", "Product")
                        .WithMany("SellingSlots")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooStores.Application.DtoTypes.Stores.VetStoreEntity", null)
                        .WithMany("avaibabProducts")
                        .HasForeignKey("VetStoreEntityId");

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ProductSlotEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ProductSlotEntityId");

                            b1.ToTable("SellingSlots");

                            b1.WithOwner()
                                .HasForeignKey("ProductSlotEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ProductSlotEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductSlotEntityId");

                            b1.ToTable("SellingSlots");

                            b1.WithOwner()
                                .HasForeignKey("ProductSlotEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.ProductTypeEntity", b =>
                {
                    b.HasOne("ZooStores.Application.DtoTypes.Products.Categories.ProductCategoryEntity", "Category")
                        .WithMany("ProductTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ProductTypeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ProductTypeEntityId");

                            b1.ToTable("ProductTypes");

                            b1.WithOwner()
                                .HasForeignKey("ProductTypeEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ProductTypeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductTypeEntityId");

                            b1.ToTable("ProductTypes");

                            b1.WithOwner()
                                .HasForeignKey("ProductTypeEntityId");
                        });

                    b.Navigation("Category");

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Clinics.VetClinicEntity", b =>
                {
                    b.HasOne("ZooStores.Application.DtoTypes.EntityComponents.LocationEntity", "location")
                        .WithMany()
                        .HasForeignKey("locationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooStores.Application.DtoTypes.Companies.CompanyEntity", "ownerCompany")
                        .WithMany("ownedClinics")
                        .HasForeignKey("ownerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("VetClinicEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("VetClinicEntityId");

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("VetClinicEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VetClinicEntityId");

                            b1.ToTable("VetClinics");

                            b1.WithOwner()
                                .HasForeignKey("VetClinicEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("location");

                    b.Navigation("ownerCompany");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Companies.CompanyEntity", b =>
                {
                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("CompanyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("CompanyEntityId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("CompanyEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CompanyEntityId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.EntityComponents.LocationEntity", b =>
                {
                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("LocationEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("LocationEntityId");

                            b1.ToTable("LocationEntity");

                            b1.WithOwner()
                                .HasForeignKey("LocationEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("LocationEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("LocationEntityId");

                            b1.ToTable("LocationEntity");

                            b1.WithOwner()
                                .HasForeignKey("LocationEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Products.Categories.ProductCategoryEntity", b =>
                {
                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ProductCategoryEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ProductCategoryEntityId");

                            b1.ToTable("ProductCategories");

                            b1.WithOwner()
                                .HasForeignKey("ProductCategoryEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ProductCategoryEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ProductCategoryEntityId");

                            b1.ToTable("ProductCategories");

                            b1.WithOwner()
                                .HasForeignKey("ProductCategoryEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Products.Delivery.DeliveryOptionEntity", b =>
                {
                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("DeliveryOptionEntityId");

                            b1.ToTable("DeliveryOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOptionEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("DeliveryOptionEntityId");

                            b1.ToTable("DeliveryOptions");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOptionEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Products.Delivery.SelfPickupOptionEntity", b =>
                {
                    b.HasOne("ZooStores.Application.DtoTypes.EntityComponents.LocationEntity", "PickupPointLocation")
                        .WithMany()
                        .HasForeignKey("PickupPointLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("SelfPickupOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("SelfPickupOptionEntityId");

                            b1.ToTable("SelfPickupOptions");

                            b1.WithOwner()
                                .HasForeignKey("SelfPickupOptionEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("SelfPickupOptionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("SelfPickupOptionEntityId");

                            b1.ToTable("SelfPickupOptions");

                            b1.WithOwner()
                                .HasForeignKey("SelfPickupOptionEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("PickupPointLocation");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Stores.VetStoreEntity", b =>
                {
                    b.HasOne("ZooStores.Application.DtoTypes.EntityComponents.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZooStores.Application.DtoTypes.Companies.CompanyEntity", "ownerCompany")
                        .WithMany("ownedStores")
                        .HasForeignKey("ownerCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("VetStoreEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("VetStoreEntityId");

                            b1.ToTable("VetStores");

                            b1.WithOwner()
                                .HasForeignKey("VetStoreEntityId");
                        });

                    b.OwnsOne("ZooStorages.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("VetStoreEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("VetStoreEntityId");

                            b1.ToTable("VetStores");

                            b1.WithOwner()
                                .HasForeignKey("VetStoreEntityId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("ownerCompany");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.DynamicAttributes.ProductAttributeTypeEntity", b =>
                {
                    b.Navigation("AttributesOfType");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.Components.ProductEntity", b =>
                {
                    b.Navigation("ExtendedAttributes");

                    b.Navigation("Reviews");

                    b.Navigation("SellingSlots");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ZooStorages.Domain.DataEntities.Products.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductsOfType");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Companies.CompanyEntity", b =>
                {
                    b.Navigation("ownedClinics");

                    b.Navigation("ownedStores");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Products.Categories.ProductCategoryEntity", b =>
                {
                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("ZooStores.Application.DtoTypes.Stores.VetStoreEntity", b =>
                {
                    b.Navigation("avaibabProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
