// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zoobee.Infrastructure.Parsers.Data;

#nullable disable

namespace Zoobee.Web.Migrations.ParsersDb
{
    [DbContext(typeof(ParsersDbContext))]
    partial class ParsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Core.Entities.ScrapingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScrapingTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScrapingTaskId");

                    b.ToTable("ScrapingDatas");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Core.Entities.ScrapingTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomFrequencyHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextTryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("Status", "NextTryAt");

                    b.ToTable("ScrapingTasks");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Core.Entities.ScrapingData", b =>
                {
                    b.HasOne("Zoobee.Infrastructure.Parsers.Core.Entities.ScrapingTask", "ScrapingTask")
                        .WithMany("History")
                        .HasForeignKey("ScrapingTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ScrapingDataId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ScrapingDataId");

                            b1.ToTable("ScrapingDatas");

                            b1.WithOwner()
                                .HasForeignKey("ScrapingDataId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ScrapingDataId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ScrapingDataId");

                            b1.ToTable("ScrapingDatas");

                            b1.WithOwner()
                                .HasForeignKey("ScrapingDataId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("ScrapingTask");
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Core.Entities.ScrapingTask", b =>
                {
                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.SoftDelete.ISoftDeletableEntity+SoftDeleteData", "DeleteData", b1 =>
                        {
                            b1.Property<Guid>("ScrapingTaskId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DeletedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<bool>("IsDeleted")
                                .HasColumnType("boolean");

                            b1.HasKey("ScrapingTaskId");

                            b1.ToTable("ScrapingTasks");

                            b1.WithOwner()
                                .HasForeignKey("ScrapingTaskId");
                        });

                    b.OwnsOne("Zoobee.Domain.DataEntities.Base.IEntityMetadata+EntityMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ScrapingTaskId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset?>("LastModified")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("ScrapingTaskId");

                            b1.ToTable("ScrapingTasks");

                            b1.WithOwner()
                                .HasForeignKey("ScrapingTaskId");
                        });

                    b.Navigation("DeleteData")
                        .IsRequired();

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Zoobee.Infrastructure.Parsers.Core.Entities.ScrapingTask", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
